### ISSUE TITLE
Installing 2.23 versions of LilyPond

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [flathub/org.frescobaldi.Frescobaldi#10]
In the LilyPond 2.23 series, installers are no longer provided. Instead, we provide static binaries that can be unpacked and run right away.

The tutorial on installing LilyPond and Frescobaldi in the Learning Manual (https://lilypond.org/doc/v2.23/Documentation/learning/graphical-setup-under-gnu_002flinux) says you can unpack the LilyPond binary "anywhere, you just have not to move it afterwards", and the example does it in `~`, but this does not work with Frescobaldi from Flatpak because access is restricted. It does work to put it in `~/Documents` for example. (See the user-fr thread https://lists.gnu.org/archive/html/lilypond-user-fr/2022-09/msg00049.html with people encountering this problem.)

- Would it be possible to relax permissions so that installing in `~` would work?
- If not, could this be mentioned in the Flathub package description, or better yet, could the Flathub version of Frescobaldi be patched to display a helpful error message if the `lilypond` binary can't be accessed due to permission issues? This is quite important, since for the upcoming stable release LilyPond 2.24 most users will have to set up LilyPond by providing a path to the binary in the settings.

Any thoughts @fedelibre?

**Comment by fedelibre** [comment]
I would prefer following flatpak best practices and not giving full access to the home directory.
I can add a short explanation in the README file. In a nutshell, the steps are:

1. Grant the permission to the desired directory, anything in ~ (for example `~/.local/lilypond`), using the Flatseal app or the command-line flatpak.
2. Launch Frescobaldi and add the path to this binary in the LilyPond preferences.

**Comment by fedelibre** [comment]
> Would it be possible to make this work for access to LilyPond binaries as well?

Yes, but it would mean allowing access to the whole home directory, which is not what I would want to set by default (see 1st point above).

We may agree on a standard default directory for these binaries, which could be enabled by default in the flatpak app. For example `~/lilypond` or `~/.lilypond` or `~/.local/lilypond`. That way users who unpack the binaries in this location would not have to tweak the permissions at all.

**Comment by hfiguiere** [comment]
> Would it be possible to make this work for access to LilyPond binaries as well?

If you mean runing "host binaries" inside the flatpak sandbox, I have to say this is a bad idea. There is a reason why Flatpak provides its sdk+runtime.

**Comment by fedelibre** [comment]
@hfiguiere Many LilyPond users (and especially the developers like Jean) need to run custom versions of LilyPond.

The point here is that from Flatpak point of view this should be discouraged: it should not be the default, but I think I can add a quick explanation in the README for those who really need this.
