### ISSUE TITLE
python-ly version

### ISSUE THREAD

**Issue by jeanas** [flathub/org.frescobaldi.Frescobaldi#32]
The Flatpak doesn't have the latest python-ly version sources, only the latest release, which doesn't have the LilyPond 2.24 update.

Maybe we should do a python-ly release first and then bump it here...

**Comment by fedelibre** [comment]
> Maybe we should do a python-ly release first and then bump it here...

Yes. In Flatpak manifests tarballs are usually preferred to git commits/tags.
